/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.puissance4;

public class App {
    public static void main(String[] args) {
        Database db = new Database();
    }
}
